<?php
$config = 
    array( 'inserirContrato' => array(
        'nu_contrato'			 => array(  'field' => 'nu_contrato', 'label' => 'nu_contrato', 'rules' => 'trim|required|is_unique[contrato.nu_Contrato]'),
        'vl_contrato'			 => array(  'field' => 'vl_contrato', 'label' => 'vl_contrato', 'rules' => 'trim|required'),
        'cd_moeda'   			 => array(  'field' => 'cd_moeda',    'label' => 'cd_moeda',    'rules' => 'trim|required'),
        'tp_contrato'			 => array(  'field' => 'tp_contrato', 'label' => 'tp_contrato', 'rules' => 'trim|required'),
        'nu_processoLicitatorio' => array(  'field' => 'nu_processoLicitatorio', 'label' => 'nu_processoLicitatorio', 'rules' => 'trim|required'),
        'dt_assinaturaContrato'  => array(  'field' => 'dt_assinaturaContrato', 'label' => 'dt_assinaturaContrato', 'rules' => 'trim|required|valid_date'),
        'dt_vencimentoContrato'  => array(  'field' => 'dt_vencimentoContrato', 'label' => 'dt_vencimentoContrato', 'rules' => 'trim|required|valid_date'),
		'tp_pessoaContratado'	 => array(  'field' => 'tp_pessoaContratado', 'label' => 'tp_pessoaContratado', 'rules' => 'trim|required'),
        'cd_cicContratado'		 => array(  'field' => 'cd_cicContratado', 'label' => 'cd_cicContratado', 'rules' => 'trim|required'),
        'nm_contratado'   		 => array(  'field' => 'nm_contratado',    'label' => 'nm_contratado',    'rules' => 'trim|required'),
        'de_objetivoContrato'	 => array(  'field' => 'de_objetivoContrato', 'label' => 'de_objetivoContrato', 'rules' => 'trim|required'),
        'nu_diarioOficial' 		 => array(  'field' => 'nu_diarioOficial', 'label' => 'nu_diarioOficial', 'rules' => 'trim|required'),
        'dt_publicacao'  		 => array(  'field' => 'dt_publicacao', 'label' => 'dt_publicacao', 'rules' => 'trim|required|valid_date'),
		'nu_certidaoINSS'  		 => array(  'field' => 'nu_certidaoINSS', 'label' => 'nu_certidaoINSS', 'rules' => 'trim|required'),
		'dt_certidaoINSS'  		 => array(  'field' => 'dt_certidaoINSS', 'label' => 'dt_certidaoINSS', 'rules' => 'trim|valid_date|required'),
		'dt_validadeINSS'  		 => array(  'field' => 'dt_validadeINSS', 'label' => 'dt_validadeINSS', 'rules' => 'trim|valid_date|required'),
		'nu_certidaoFGTS'  		 => array(  'field' => 'nu_certidaoFGTS', 'label' => 'nu_certidaoFGTS', 'rules' => 'trim|required'),
		'dt_certidaoFGTS'  		 => array(  'field' => 'dt_certidaoFGTS', 'label' => 'dt_certidaoFGTS', 'rules' => 'trim|valid_date|required'),
		'dt_validadeFGTS'  		 => array(  'field' => 'dt_validadeFGTS', 'label' => 'dt_validadeFGTS', 'rules' => 'trim|valid_date|required'),
		'nu_certidaoFazendaMunicipal'  		 => array(  'field' => 'nu_certidaoFazendaMunicipal', 'label' => 'nu_certidaoFazendaMunicipal', 'rules' => 'trim|required'),
		'dt_certidaoFazendaMunicipal'  		 => array(  'field' => 'dt_certidaoFazendaMunicipal', 'label' => 'dt_certidaoFazendaMunicipal', 'rules' => 'trim|valid_date|required'),
		'dt_validadeFazendaMunicipal'  		 => array(  'field' => 'dt_validadeFazendaMunicipal', 'label' => 'dt_validadeFazendaMunicipal', 'rules' => 'trim|valid_date|required'),
		'nu_certidaoFazendaEstadual'  		 => array(  'field' => 'nu_certidaoFazendaEstadual', 'label' => 'nu_certidaoFazendaEstadual', 'rules' => 'trim|required'),
		'dt_certidaoFazendaEstadual'  		 => array(  'field' => 'dt_certidaoFazendaEstadual', 'label' => 'dt_certidaoFazendaEstadual', 'rules' => 'trim|valid_date|required'),
		'dt_validadeFazendaEstadual'  		 => array(  'field' => 'dt_validadeFazendaEstadual', 'label' => 'dt_validadeFazendaEstadual', 'rules' => 'trim|valid_date|required'),
		'nu_certidaoFazendaFederal'  		 => array(  'field' => 'nu_certidaoFazendaFederal', 'label' => 'nu_certidaoFazendaFederal', 'rules' => 'trim|required'),
		'dt_certidaoFazendaFederal'  		 => array(  'field' => 'dt_certidaoFazendaFederal', 'label' => 'dt_certidaoFazendaFederal', 'rules' => 'trim|valid_date|required'),
		'dt_validadeFazendaFederal'  		 => array(  'field' => 'dt_validadeFazendaFederal', 'label' => 'dt_validadeFazendaFederal', 'rules' => 'trim|valid_date|required'),
		'nu_certidaoOutras'  		 => array(  'field' => 'nu_certidaoOutras', 'label' => 'nu_certidaoOutras', 'rules' => 'trim|required'),
		'dt_certidaoOutras'  		 => array(  'field' => 'dt_certidaoOutras', 'label' => 'dt_certidaoOutras', 'rules' => 'trim|valid_date|required'),
		'dt_validadeOutras'  		 => array(  'field' => 'dt_validadeOutras', 'label' => 'dt_validadeOutras', 'rules' => 'trim|valid_date|required'),
		'nu_certidaoCNDT'  		 => array(  'field' => 'nu_certidaoCNDT', 'label' => 'nu_certidaoCNDT', 'rules' => 'trim|required'),
		'dt_certidaoCNDT'  		 => array(  'field' => 'dt_certidaoCNDT', 'label' => 'dt_certidaoCNDT', 'rules' => 'trim|valid_date|required'),
		'dt_validadeCNDT'  		 => array(  'field' => 'dt_validadeCNDT', 'label' => 'dt_validadeCNDT', 'rules' => 'trim|valid_date|required'),
		'nu_ContratoSuperior'    => array(  'field' => 'nu_ContratoSuperior',    'label' => 'nu_ContratoSuperior',    'rules' => 'trim|required'),
        'tp_Aditivo'			 => array(  'field' => 'tp_Aditivo', 'label' => 'tp_Aditivo', 'rules' => 'trim|required'),
		'cnpj_UgContrato'    => array(  'field' => 'cnpj_UgContrato',    'label' => 'cnpj_UgContrato',    'rules' => 'trim|required'),
        'competencia'			 => array(  'field' => 'competencia', 'label' => 'competencia', 'rules' => 'trim|required'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')
                                    ),
            'inserirConvenio' => array(
        'nu_Convenio' 		     => array( 'field' => 'nu_Convenio',      'label' => 'nu_Convenio',       'rules' => 'trim|required|is_unique[convenio.nu_Convenio]'),
        'vl_Convenio' 		     => array( 'field' => 'vl_Convenio',      'label' => 'vl_Convenio',       'rules' => 'trim|required'),
        'cd_MoedaConvenio'       => array( 'field' => 'cd_MoedaConvenio', 'label' => 'cd_MoedaConvenio',  'rules' => 'required'),
        'tp_Convenio'    	     => array( 'field' => 'tp_Convenio',      'label' => 'tp_Convenio',       'rules' => 'required'),
		'dt_AssinaturaConvenio'  => array( 'field' => 'dt_AssinaturaConvenio', 'label' => 'dt_AssinaturaConvenio',  'rules' => 'required|valid_date'),
		'dt_VencimentoConvenio'  => array( 'field' => 'dt_VencimentoConvenio', 'label' => 'dt_VencimentoConvenio',  'rules' => 'required|valid_date'),
		'de_ObjetivoConvenio'    => array( 'field' => 'de_ObjetivoConvenio',   'label' => 'de_ObjetivoConvenio',    'rules' => 'trim|required'),
		'nu_DiarioOficial'       => array( 'field' => 'nu_DiarioOficial',   'label' => 'nu_DiarioOficial',    'rules' => 'trim|required'),
		'dt_PublicacaoConvenio'  => array( 'field' => 'dt_PublicacaoConvenio',   'label' => 'dt_PublicacaoConvenio',    'rules' => 'required|valid_date'),
		'nu_LeiAutorizativa'     => array( 'field' => 'nu_LeiAutorizativa',   'label' => 'nu_LeiAutorizativa',    'rules' => 'trim|required'),
		'dt_LeiAutorizativa'     => array( 'field' => 'dt_LeiAutorizativa',   'label' => 'dt_LeiAutorizativa',    'rules' => 'required|valid_date'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')
                                    ),
            'inserirParticipanteConvenio' => array(
        'nu_Convenio'			 => array(  'field' => 'nu_Convenio', 'label' => 'nu_Convenio', 'rules' => 'trim|required'),
        'tp_PessoaParticipante'	 => array(  'field' => 'tp_PessoaParticipante', 'label' => 'tp_PessoaParticipante', 'rules' => 'trim|required'),
        'nm_Participante'   	 => array(  'field' => 'nm_Participante',    'label' => 'nm_Participante',    'rules' => 'trim|required'),
        'cd_CicParticipante'	 => array(  'field' => 'cd_CicParticipante', 'label' => 'cd_CicParticipante', 'rules' => 'trim|required'),
        'vl_Participacao'        => array(  'field' => 'vl_Participacao', 'label' => 'vl_Participacao', 'rules' => 'trim|required'),
        'vl_PercentualParticipacao'  => array(  'field' => 'vl_PercentualParticipacao', 'label' => 'vl_PercentualParticipacao', 'rules' => 'trim|required'),
        'nu_CertidaoCASAN'       => array(  'field' => 'nu_CertidaoCASAN', 'label' => 'nu_CertidaoCASAN', 'rules' => 'trim|required'),
		'dt_CertidaoCASAN'	     => array(  'field' => 'dt_CertidaoCASAN', 'label' => 'dt_CertidaoCASAN', 'rules' => 'trim|required|valid_date'),
        'dt_ValidadeCertidaoCASAN' => array(  'field' => 'dt_ValidadeCertidaoCASAN', 'label' => 'dt_ValidadeCertidaoCASAN', 'rules' => 'trim|required|valid_date'),
        'nu_CertidaoCELESC'     => array(  'field' => 'nu_CertidaoCELESC',    'label' => 'nu_CertidaoCELESC',    'rules' => 'trim|required'),
        'dt_CertidaoCELESC'	 => array(  'field' => 'dt_CertidaoCELESC', 'label' => 'dt_CertidaoCELESC', 'rules' => 'trim|required|valid_date'),
        'dt_ValidadeCertidaoCELESC' => array(  'field' => 'dt_ValidadeCertidaoCELESC', 'label' => 'dt_ValidadeCertidaoCELESC', 'rules' => 'trim|required|valid_date'),
        'nu_CertidaoFazendaMunicipal'  		 => array(  'field' => 'nu_CertidaoFazendaMunicipal', 'label' => 'nu_CertidaoFazendaMunicipal', 'rules' => 'trim|required'),
		'dt_CertidaoFazendaMunicipal'  		 => array(  'field' => 'dt_CertidaoFazendaMunicipal', 'label' => 'dt_CertidaoFazendaMunicipal', 'rules' => 'trim|required|valid_date'),
		'dt_ValidadeFazendaMunicipal'  		 => array(  'field' => 'dt_ValidadeFazendaMunicipal', 'label' => 'dt_ValidadeFazendaMunicipal', 'rules' => 'trim|required|valid_date'),
		'nu_CertidaoIPESC'  		 => array(  'field' => 'nu_CertidaoIPESC', 'label' => 'nu_CertidaoIPESC', 'rules' => 'trim|required'),
		'dt_CertidaoIPESC'  		 => array(  'field' => 'dt_CertidaoIPESC', 'label' => 'dt_CertidaoIPESC', 'rules' => 'trim|required|valid_date'),
		'dt_ValidadeCertidaoIPESC'  => array(  'field' => 'dt_ValidadeCertidaoIPESC', 'label' => 'dt_ValidadeCertidaoIPESC', 'rules' => 'trim|required|valid_date'),
		'nu_CertidaoFazendaFederal'  		 => array(  'field' => 'nu_CertidaoFazendaFederal', 'label' => 'nu_CertidaoFazendaFederal', 'rules' => 'trim|required'),
		'dt_CertidaoFazendaFederal'  		 => array(  'field' => 'dt_CertidaoFazendaFederal', 'label' => 'dt_CertidaoFazendaFederal', 'rules' => 'trim|required|valid_date'),
		'dt_ValidadeFazendaFederal'  		 => array(  'field' => 'dt_ValidadeFazendaFederal', 'label' => 'dt_ValidadeFazendaFederal', 'rules' => 'trim|required|valid_date'),
		'nu_CertidaoCNDT'  		 => array(  'field' => 'nu_CertidaoCNDT', 'label' => 'nu_CertidaoCNDT', 'rules' => 'trim|required'),
		'dt_certidaoCNDT'  		 => array(  'field' => 'dt_certidaoCNDT', 'label' => 'dt_certidaoCNDT', 'rules' => 'trim|valid_date|required'),
		'dt_validadeCNDT'  		 => array(  'field' => 'dt_validadeCNDT', 'label' => 'dt_validadeCNDT', 'rules' => 'trim|valid_date|required'),
		'nu_CertidaoOutras'  		 => array(  'field' => 'nu_CertidaoOutras', 'label' => 'nu_CertidaoOutras', 'rules' => 'trim|required'),
		'dt_CertidaoOutras'  		 => array(  'field' => 'dt_CertidaoOutras', 'label' => 'dt_CertidaoOutras', 'rules' => 'trim|valid_date|required'),
		'dt_ValidadeOutras'  		 => array(  'field' => 'dt_ValidadeOutras', 'label' => 'dt_ValidadeOutras', 'rules' => 'trim|valid_date|required'),
		'tp_EsferaConvenio'  		 => array(  'field' => 'tp_EsferaConvenio', 'label' => 'tp_EsferaConvenio', 'rules' => 'trim|required'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')
                                      ),
           'inserirLicitacao' => array(
        'nu_ProcessoLicitatorio'  => array('field' => 'nu_ProcessoLicitatorio', 'label' => 'nu_ProcessoLicitatorio', 'rules' => 'trim|required|is_unique[licitacao.nu_ProcessoLicitatorio]'),
        'nu_DiarioOficial'  => array('field' => 'nu_DiarioOficial', 'label' => 'nu_DiarioOficial', 'rules' => 'trim|required'),
		'dt_PublicacaoEdital'  => array('field' => 'dt_PublicacaoEdital', 'label' => 'dt_PublicacaoEdital', 'rules' => 'trim|required|valid_date'),
		'cd_Modalidade'  => array('field' => 'cd_Modalidade', 'label' => 'cd_Modalidade', 'rules' => 'required'),
		'de_ObjetoLicitacao'  => array('field' => 'de_ObjetoLicitacao', 'label' => 'de_ObjetoLicitacao', 'rules' => 'trim|required'),
		'vl_TotalPrevisto'  => array('field' => 'vl_TotalPrevisto', 'label' => 'vl_TotalPrevisto', 'rules' => 'trim|required'),
		'nu_Edital'  => array('field' => 'nu_Edital', 'label' => 'nu_Edital', 'rules' => 'trim|required'),
		'tp_Licitacao'  => array('field' => 'tp_Licitacao', 'label' => 'tp_Licitacao', 'rules' => 'trim|required'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')    
           							),
		   'inserirItemLicitacao' => array(
        'nu_ProcessoLicitatorio'  => array('field' => 'nu_ProcessoLicitatorio', 'label' => 'nu_ProcessoLicitatorio', 'rules' => 'trim|required'),
        'nu_SequenciaItem'  => array('field' => 'nu_SequenciaItem', 'label' => 'nu_SequenciaItem', 'rules' => 'trim|required'),
		'qt_ItemLicitado'  => array('field' => 'qt_ItemLicitado', 'label' => 'qt_ItemLicitado', 'rules' => 'trim|required'),
		'dt_HomologacaoItem'  => array('field' => 'dt_HomologacaoItem', 'label' => 'dt_HomologacaoItem', 'rules' => 'trim|required|valid_date'),
		'dt_PublicacaoHomologacao'  => array('field' => 'dt_PublicacaoHomologacao', 'label' => 'dt_PublicacaoHomologacao', 'rules' => 'trim|required|valid_date'),
		'un_MedidaItem'  => array('field' => 'un_MedidaItem', 'label' => 'un_MedidaItem', 'rules' => 'trim|required'),
		'st_Item'  => array('field' => 'st_Item', 'label' => 'st_Item', 'rules' => 'trim|required'),
		'de_ItemLicitacao'  => array('field' => 'de_ItemLicitacao', 'label' => 'de_ItemLicitacao', 'rules' => 'trim|required'),
		'ct_ItemLote'  => array('field' => 'ct_ItemLote', 'label' => 'ct_ItemLote', 'rules' => 'trim|required'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')    
           							),
		   'inserirCotacao' => array(
        'nu_ProcessoLicitatorio'  => array('field' => 'nu_ProcessoLicitatorio', 'label' => 'nu_ProcessoLicitatorio', 'rules' => 'trim|required'),
        'nu_SequenciaItem'  => array('field' => 'nu_SequenciaItem', 'label' => 'nu_SequenciaItem', 'rules' => 'trim|required'),
		'tp_Pessoa'  => array('field' => 'tp_Pessoa', 'label' => 'tp_Pessoa', 'rules' => 'trim|required'),
		'cd_CicParticipante'  => array('field' => 'cd_CicParticipante', 'label' => 'cd_CicParticipante', 'rules' => 'trim|required'),
		'vl_TotalCotadoItem'  => array('field' => 'vl_TotalCotadoItem', 'label' => 'vl_TotalCotadoItem', 'rules' => 'trim|required'),
		'tp_Valor'  => array('field' => 'tp_Valor', 'label' => 'tp_Valor', 'rules' => 'trim|required'),
		'qt_ItemCotado'  => array('field' => 'qt_ItemCotado', 'label' => 'qt_ItemCotado', 'rules' => 'trim|required'),
		'cd_VencedorPerdedor'  => array('field' => 'cd_VencedorPerdedor', 'label' => 'cd_VencedorPerdedor', 'rules' => 'trim|required'),
		'ct_ItemLote'  => array('field' => 'ct_ItemLote', 'label' => 'ct_ItemLote', 'rules' => 'trim|required'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')
		 							),
		'inserirCertidao' => array(
        'nu_ProcessoLicitatorio'  => array('field' => 'nu_ProcessoLicitatorio', 'label' => 'nu_ProcessoLicitatorio', 'rules' => 'trim|required'),
        'cd_CicParticipante'  => array('field' => 'cd_CicParticipante', 'label' => 'cd_CicParticipante', 'rules' => 'trim|required'),
		'tp_Certidao'  => array('field' => 'tp_Certidao', 'label' => 'tp_Certidao', 'rules' => 'trim|required'),
		'tp_Pessoa'  => array('field' => 'tp_Pessoa', 'label' => 'tp_Pessoa', 'rules' => 'trim|required'),
		'nu_Certidao'  => array('field' => 'nu_Certidao', 'label' => 'nu_Certidao', 'rules' => 'trim|required'),
		'dt_EmissaoCertidao'  => array('field' => 'dt_EmissaoCertidao', 'label' => 'dt_EmissaoCertidao', 'rules' => 'trim|required|valid_date'),
		'dt_ValidadeCertidao'  => array('field' => 'dt_ValidadeCertidao', 'label' => 'dt_ValidadeCertidao', 'rules' => 'trim|required|valid_date'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')
		 						),
		'inserirParticipanteLicitacao' => array(
        'nu_ProcessoLicitatorio'  => array('field' => 'nu_ProcessoLicitatorio', 'label' => 'nu_ProcessoLicitatorio', 'rules' => 'trim|required'),
        'cd_CicParticipante'  => array('field' => 'cd_CicParticipante', 'label' => 'cd_CicParticipante', 'rules' => 'trim|required'),
		'nm_Participante'  => array('field' => 'nm_Participante', 'label' => 'nm_Participante', 'rules' => 'trim|required'),
		'tp_Pessoa'  => array('field' => 'tp_Pessoa', 'label' => 'tp_Pessoa', 'rules' => 'trim|required'),
		'tp_Participacao'  => array('field' => 'tp_Participacao', 'label' => 'tp_Participacao', 'rules' => 'trim|required'),
		'cd_CGCConsorcio'  => array('field' => 'cd_CGCConsorcio', 'label' => 'cd_CGCConsorcio', 'rules' => 'trim|required'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')
		 						),
		'inserirContratoEmpenho' => array(
        'nu_Contrato'  => array('field' => 'nu_Contrato', 'label' => 'nu_Contrato', 'rules' => 'trim|required'),
        'nu_NotaEmpenho'  => array('field' => 'nu_NotaEmpenho', 'label' => 'nu_NotaEmpenho', 'rules' => 'trim|required'),
		'ano_Empenho'  => array('field' => 'ano_Empenho', 'label' => 'ano_Empenho', 'rules' => 'trim|required'),
		'cd_UnidadeOrcamentaria'  => array('field' => 'cd_UnidadeOrcamentaria', 'label' => 'cd_UnidadeOrcamentaria', 'rules' => 'trim|required'),
		'nu_NotaEmpenho2'  => array('field' => 'nu_NotaEmpenho2', 'label' => 'nu_NotaEmpenho2', 'rules' => 'trim'),
		'nu_NotaEmpenho3'  => array('field' => 'nu_NotaEmpenho3', 'label' => 'nu_NotaEmpenho3', 'rules' => 'trim'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')
								),
		'inserirConvenioEmpenho' => array(
        'nu_Convenio'  => array('field' => 'nu_Convenio', 'label' => 'nu_Convenio', 'rules' => 'trim|required'),
        'nu_NotaEmpenho'  => array('field' => 'nu_NotaEmpenho', 'label' => 'nu_NotaEmpenho', 'rules' => 'trim|required'),
		'ano_Empenho'  => array('field' => 'ano_Empenho', 'label' => 'ano_Empenho', 'rules' => 'trim|required'),
		'cd_UnidadeOrcamentaria'  => array('field' => 'cd_UnidadeOrcamentaria', 'label' => 'cd_UnidadeOrcamentaria', 'rules' => 'trim|required'),
		'nu_NotaEmpenho2'  => array('field' => 'nu_NotaEmpenho2', 'label' => 'nu_NotaEmpenho2', 'rules' => 'trim'),
		'nu_NotaEmpenho3'  => array('field' => 'nu_NotaEmpenho3', 'label' => 'nu_NotaEmpenho3', 'rules' => 'trim'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')
								),
		'inserirLicitacaoEmpenho' => array(
        'nu_licitacao'  => array('field' => 'nu_licitacao', 'label' => 'nu_licitacao', 'rules' => 'trim|required'),
        'nu_NotaEmpenho'  => array('field' => 'nu_NotaEmpenho', 'label' => 'nu_NotaEmpenho', 'rules' => 'trim|required'),
		'ano_Empenho'  => array('field' => 'ano_Empenho', 'label' => 'ano_Empenho', 'rules' => 'trim|required'),
		'cd_UnidadeOrcamentaria'  => array('field' => 'cd_UnidadeOrcamentaria', 'label' => 'cd_UnidadeOrcamentaria', 'rules' => 'trim|required'),
		'nu_NotaEmpenho2'  => array('field' => 'nu_NotaEmpenho2', 'label' => 'nu_NotaEmpenho2', 'rules' => 'trim'),
		'nu_NotaEmpenho3'  => array('field' => 'nu_NotaEmpenho3', 'label' => 'nu_NotaEmpenho3', 'rules' => 'trim'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')
								),
		'inserirPublicacao' => array(
        'nu_ProcessoLicitatorio'  => array('field' => 'nu_ProcessoLicitatorio', 'label' => 'nu_ProcessoLicitatorio', 'rules' => 'trim|required'),
        'dt_PublicacaoEdital'  => array('field' => 'dt_PublicacaoEdital', 'label' => 'dt_PublicacaoEdital', 'rules' => 'trim|required|valid_date'),
		'nu_SequencialPublicacao'  => array('field' => 'nu_SequencialPublicacao', 'label' => 'nu_SequencialPublicacao', 'rules' => 'trim|required'),
		'nm_veiculoComunicacao'  => array('field' => 'nm_veiculoComunicacao', 'label' => 'nm_veiculoComunicacao', 'rules' => 'trim|required'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')
								),
		'inserirLicitacaoDotacao' => array(
        'nu_ProcessoLicitatorio'  => array('field' => 'nu_ProcessoLicitatorio', 'label' => 'nu_ProcessoLicitatorio', 'rules' => 'trim|required'),
        'cd_CategoriaEconomica'  => array('field' => 'cd_CategoriaEconomica', 'label' => 'cd_CategoriaEconomica', 'rules' => 'trim|required'),
		'cd_GrupoNatureza'  => array('field' => 'cd_GrupoNatureza', 'label' => 'cd_GrupoNatureza', 'rules' => 'trim|required'),
		'cd_ModalidadeAplicacao'  => array('field' => 'cd_ModalidadeAplicacao', 'label' => 'cd_ModalidadeAplicacao', 'rules' => 'trim|required'),
		'cd_Elemento'  => array('field' => 'cd_Elemento', 'label' => 'cd_Elemento', 'rules' => 'trim|required'),
        'cd_UnidadeOrcamentaria'  => array('field' => 'cd_UnidadeOrcamentaria', 'label' => 'cd_UnidadeOrcamentaria', 'rules' => 'trim|required'),
		'cd_FonteRecurso'  => array('field' => 'cd_FonteRecurso', 'label' => 'cd_FonteRecurso', 'rules' => 'trim|required'),
		'nu_AcaoGoverno'  => array('field' => 'nu_AcaoGoverno', 'label' => 'nu_AcaoGoverno', 'rules' => 'trim|required'),
		'cd_SubFuncao'  => array('field' => 'cd_SubFuncao', 'label' => 'cd_SubFuncao', 'rules' => 'trim|required'),
		'cd_Funcao'  => array('field' => 'cd_Funcao', 'label' => 'cd_Funcao', 'rules' => 'trim|required'),
        'cd_Programa'  => array('field' => 'cd_Programa', 'label' => 'cd_Programa', 'rules' => 'trim|required'),
		'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')
								),
		'inserirConta' => array(
			'ano_criacao'  => array('field' => 'ano_criacao', 'label' => 'ano_criacao', 'rules' => 'trim|required'),
			'cd_conta'  => array('field' => 'cd_conta', 'label' => 'cd_conta', 'rules' => 'trim|required|is_unique[conta.cd_conta]'),
			'nome_conta'  => array('field' => 'nome_conta', 'label' => 'nome_conta', 'rules' => 'trim|required'),
			'nivel_conta'  => array('field' => 'nivel_conta', 'label' => 'nivel_conta', 'rules' => 'trim|required'),
			'cd_recebeLancamento'  => array('field' => 'cd_recebeLancamento', 'label' => 'cd_recebeLancamento', 'rules' => 'trim|required'),
			'id_tipoSaldo'  => array('field' => 'id_tipoSaldo', 'label' => 'id_tipoSaldo', 'rules' => 'trim|required'),
			'cd_contaSuperior'  => array('field' => 'cd_contaSuperior', 'label' => 'cd_contaSuperior', 'rules' => 'trim|required'),
			'cd_reduzido'  => array('field' => 'cd_reduzido', 'label' => 'cd_reduzido', 'rules' => 'trim|required'),
			'cd_itemOrcamentario'  => array('field' => 'cd_itemOrcamentario', 'label' => 'cd_itemOrcamentario', 'rules' => 'trim|required'),
			'cd_banco'  => array('field' => 'cd_banco', 'label' => 'cd_banco', 'rules' => 'trim|required'),
			'cd_agencia'  => array('field' => 'cd_agencia', 'label' => 'cd_agencia', 'rules' => 'trim|required'),
			'nu_conta'  => array('field' => 'nu_conta', 'label' => 'nu_conta', 'rules' => 'trim|required'),
			'tp_conta'  => array('field' => 'tp_conta', 'label' => 'tp_conta', 'rules' => 'trim|required'),
			'ano_criacaoSuperior'  => array('field' => 'ano_criacaoSuperior', 'label' => 'ano_criacaoSuperior', 'rules' => 'trim|required'),
			'mes'  		 => array(  'field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required')
								),		
		'inserir_adesao_ata_licitacao' => array(
			'nu_ProcessoCompra'  => array('field' => 'nu_ProcessoCompra', 'label' => 'nu_ProcessoCompra', 'rules' => 'trim|required'),
			'nu_Ata'  => array('field' => 'nu_Ata', 'label' => 'nu_Ata', 'rules' => 'trim|required'),
			'nu_ProcessoLicitatorio'  => array('field' => 'nu_ProcessoLicitatorio', 'label' => 'nu_ProcessoLicitatorio', 'rules' => 'trim|required'),
			'dt_Publicacao'  => array('field' => 'dt_Publicacao', 'label' => 'dt_Publicacao', 'rules' => 'trim|required|valid_date'),
			'dt_Validade'  => array('field' => 'dt_Validade', 'label' => 'dt_Validade', 'rules' => 'trim|required|valid_date'),
			'dt_Adesao'  => array('field' => 'dt_Adesao', 'label' => 'dt_Adesao', 'rules' => 'trim|required|valid_date'),
			'tp_Adesao'  => array('field' => 'tp_Adesao', 'label' => 'tp_Adesao', 'rules' => 'trim|required'),
			'nu_Dirario'  => array('field' => 'nu_Dirario', 'label' => 'nu_Dirario', 'rules' => 'trim|required'),
			'mes'  => array('field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required'),
		),
		'inserir_item_adesao_ata'  => array(
			'qt_Item'  => array('field' => 'qt_Item', 'label' => 'qt_Item', 'rules' => 'trim|required'),
			'se_ItemAta'  => array('field' => 'se_ItemAta', 'label' => 'se_ItemAta', 'rules' => 'trim|required'),
			'vl_Item'  => array('field' => 'vl_Item', 'label' => 'vl_Item', 'rules' => 'trim|required'),
			'un_Medida'  => array('field' => 'un_Medida', 'label' => 'un_Medida', 'rules' => 'trim|required'),
			'de_Item'  => array('field' => 'de_Item', 'label' => 'de_Item', 'rules' => 'trim|required'),
			'id_adesao_ata'  => array('field' => 'id_adesao_ata', 'label' => 'id_adesao_ata', 'rules' => 'trim|required'),
			'mes'  => array('field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required'),
		),
		'inserir_movcon_inicial'  => array(
			'id_conta'  => array('field' => 'id_conta', 'label' => 'id_conta', 'rules' => 'trim|required'),
			'tp_movimento'  => array('field' => 'tp_movimento', 'label' => 'tp_movimento', 'rules' => 'trim|required'),
			'vl_movDebito'  => array('field' => 'vl_movDebito', 'label' => 'vl_movDebito', 'rules' => 'trim|required'),
			'vl_movCredito'  => array('field' => 'vl_movCredito', 'label' => 'vl_movCredito', 'rules' => 'trim|required'),
			'mes'  => array('field' => 'mes', 'label' => 'mes', 'rules' => 'trim|required'),
		),
   );
?>
